### ISSUE TITLE
Is it possible to use Spring's annotation(@Service, @Autowired and @EnableScheduling) with jacpfx

### ISSUE THREAD

**Issue by suyambuganesh** [JacpFX/JacpFX#22]

**Comment by amoAHCP** [comment]
Hi, yes you can use it. By default the JacpFX spring laucher is configured in the archetype. You can choose Spring xml or programmstic configuration and all JacpFX components will be "normal" spring beans.

Andy

**Comment by suyambuganesh** [comment]
Hi Andy,

Thank you for your response. I will try it and get back to you if I have any other questions.
