### ISSUE TITLE
Provide SPI for persisting events

### ISSUE THREAD

**Issue by ganeshgitrepo** [JacpFX/JacpFX#23]
Hi Andy,

I think it would be nice to provide an SPI to enable persisting all the events generated by the user interaction with the application. Which can be useful in finding\analyzing the user behavior.

Something like durable message queue?

Thanks

**Comment by amoAHCP** [comment]
Hi,
currently it is not that easy to analyze the messages… but it should be easy to extend JacpFX to provide a SPI which allows you to track/persist the messages. Let me analyze this… but I think this could be a nice feature for 2.1.

> Am 02.03.2015 um 10:49 schrieb suyambuganesh <notifications@github.com>:
> 
> SPI

Andy
