### ISSUE TITLE
Access toolbar and menu from a (ui)component

### ISSUE THREAD

**Issue by mamayoleksandr** [JacpFX/JacpFX#27]
Am sorry, this question might be not that relevant, but am new to javafx and jacp. If there is a need to disable menu button from UI component, how would I do that?

thanks.

**Comment by amoAHCP** [comment]
Hi, the way to go is the FXComponentLayout ... you can get the reference to FXComponentLayout in any @PostConstruct method (in perspectives or components)... from the FXComponentLayout you can get your registered toolbar (north, south, west, east)... when you have your toolbar reference you can add Buttons / Regions to your toolbar in two ways:
1.) simply add(button)... than it will be managed by your perspective, if you switch to an other perspective all buttons will be hided
2.) add with id "add("id", button)"... this button is now not managed by the parent perspective and you can get the reference to this button later and set it on/off or whatever
 @PostConstruct
    public void onPostConstructComponent(final FXComponentLayout layout,
                                         final ResourceBundle resourceBundle) {
        JACPToolBar north = layout.getRegisteredToolBar(ToolbarPosition.NORTH);
        north.add("myID",new Button("hello")); // not managed by perspective
        north.add(new Button("hello2")); // managed by perspective
        Button button = north.getNodes("myID");
    }


Andy
