### ISSUE TITLE
Inaccurate exception

### ISSUE THREAD

**Issue by misty000** [JacpFX/JacpFX#31]
org.jacpfx.rcp.util.FXUtil  line 310

fxmlLoader throw an exception: javafx.fxml.LoadException: Resource "hello" not found.
/E:/devel/JacpFXSample/build/resources/main/fxml/ComponentRight.fxml:10
It means the fxml is exists, and some resource defined in fxml not found.

FXUtil report "fxml file not found ...", it is misleading.

**Comment by amoAHCP** [comment]
Hi,
this bug is fixed for Version 2.1 https://github.com/JacpFX/JacpFX/issues/9

THX for reporting
