### ISSUE TITLE
Let ClassFinder work in Gradle

### ISSUE THREAD

**Issue by misty000** [JacpFX/JacpFX#32]
gradle compile Class to "projectRoot/build/classes/main", that ClassFinder can't find Perspectives and Components in "classes". 
I rewrite ClassFinder#exctractClasses.

    private List<Class> exctractClasses(final String packageDir, List<String> files) {
        return files.stream()
                .map(Paths::get)
                .map(path -> binDirs.stream()        // find the right classpath of file
                        .filter(path::startsWith)
                        .findFirst()
                        .map(p -> p.relativize(path)))
                .filter(Optional::isPresent)
                .map(Optional::get)
                .filter(path -> path.startsWith(packageDir))
                .map(path -> path.toString().replace(File.separator, CLASS_DOT))
                .map(className -> className.substring(0, className.lastIndexOf(CLASS_FILE)))
                .filter(classFile -> !classFile.contains(CLASS_DOLLAR))
                .map(this::loadClass)
                .filter(clazz -> clazz != null)
                .collect(Collectors.toList());
    }

I don't know if it can work in maven.
This is my sample project: http://git.oschina.net/ellipse/JacpFXSample

**Comment by amoAHCP** [comment]
Hi,
I have tested it with maven on OSX and it works... have you tested it with Windows? I have to test it on a Windows VM later. THX Andy

**Comment by misty000** [comment]
Do you think empty string ("") is allowed to "getBasePackages" to find all classes?
        @Override
        protected String[] getBasePackages() {
            return new String[]{"quickstart"};
        }
If it allowed, I make some changes in "exctractClasses".
    private List<Class> exctractClasses(final String packageDir, List<String> files) {
        return files.parallelStream()
                .filter(s -> !s.contains(CLASS_DOLLAR)) // exclude "$" at start
                .map(Paths::get)                        // Path is better than String
                .map(path -> binDirs.stream()           // find the right classpath of file
                        .filter(path::startsWith)
                        .findFirst()
                        .map(p -> p.relativize(path)))
                .filter(Optional::isPresent)
                .map(op -> op.get().toString())
                .filter(path -> path.startsWith(packageDir))
                        // use startsWith instead contains
                        // because package "misty" may match "misty.Perspective" but not "org.misty.Perspective"
                .map(path -> path.replace(File.separator, CLASS_DOT))
                .map(className -> className.substring(0, className.lastIndexOf(CLASS_FILE)))
                .map(this::loadClass)
                .filter(clazz -> clazz != null)
                .collect(Collectors.toList());
    }
And it works on quickstart project with gradle on Windows
