### ISSUE TITLE
Enable 3D support

### ISSUE THREAD

**Issue by mamayoleksandr** [JacpFX/JacpFX#34]
Hi Andy,

is it possible to enabled 3d support for the scene? When creating Scene 4rth parameter (depthBuffer) should be true.
Method completeLayout() in AFXWorkbench inits Scene, but how to override or configure it?

thanks,

Alex.

**Comment by amoAHCP** [comment]
Hi Alex, I am not an JavaFX 3d expert but I have an example: https://github.com/JacpFX/JacpFX-misc/blob/master/JavaFX8Demo/src/main/java/com/trivadis/com/component/Demo4Component.java ... the component is a JacpFX component. I hope it helps...

Andy
