### ISSUE TITLE
How to register the center of BordPane as an target layout?

### ISSUE THREAD

**Issue by Mehonidas** [JacpFX/JacpFX#36]
Hi again :-),

if i write this:
```
perspectiveLayout.registerTargetLayoutComponent(BasicConfig.P_CONTACT, contentArea.getCenter());
```
I got this:
```
no targetLayout for layoutID: P_Contact found
```
P_Contact is the ID of BasicConfig.P_CONTACT.
contentArea is the name of my BorderPane in FXML and i injected it like this:
```
@FXML
private BorderPane contentArea;
```
Is it possible to register a center of BorderPane?

THX!
Greetings Meho

**Comment by JacpFX** [comment]
Hi, it looks like if your BorderPane center is null... ? Did you set any node on the center? If not you should do it (BorderPane should not provide a "default node" ) see https://docs.oracle.com/javase/8/javafx/api/javafx/scene/layout/BorderPane.html

Andy

**Comment by Mehonidas** [comment]
Hi Andy, 
thank you for your response!
You have right, I do not have a node inside the BorderPane, getCenter() return null. 
But this is the question:
If the BorderPane is the leaf of my perspective and i want fill it with a component how can i put the component to the center of the BorderPane?

greetings Meho :-)

**Comment by amoAHCP** [comment]
Hi, you always need a wrapper/container. So you can add a Group to your BorderPane center. This is more or less the way you wou would do it with plain JavaFX.

Andy
