### ISSUE TITLE
Support TabPane as TargetLayoutComponent

### ISSUE THREAD

**Issue by edvin** [JacpFX/JacpFX#40]
I'm would like to use TabPane as target (initialTargetLayoutId) for Views to mimic the editor area of an IDE, but a TabPane takes Tab instances, which are not subclasses of Node, so currently that doesn't seem possible.

I ended up creating a an FXComponent that wraps Node elements in a Tab before adding them to the TabPane, but for this I have to instantiate a  Fragment or just unmanaged JavaFX components, which means they cannot be message targets. I would really like the elements of my TabPane to be Views that I can dynamically inject into my TabPane.

Can you see a possible solution for this, or would it be possible to implement special support for TabPane?

Current use case: A search TextField in the toolbar fires a message to a CustomerService component that fetches a list of customers, then instantiates a CustomerList View and adds it as a Tab to the TabPane editor area.

Sorry if I missed something and this doesn't make sense at all, it's my first day with JacpFX. Really enjoy the concepts though :)

**Comment by amoAHCP** [comment]
Hi, sorry for delay. Yes Tab is not extending Node which is really impractical.... try https://github.com/JacpFX/JacpFX-misc/blob/master/JavaFX8Demo/src/main/java/com/trivadis/com/perspective/TabPerspective.java ... hopefully it helps you. This is just a workaround but it works.

Andy

**Comment by edvin** [comment]
Thanks :)
