### ISSUE TITLE
Use of system class loader in ClassFinder

### ISSUE THREAD

**Issue by jlepropre** [JacpFX/JacpFX#42]
Hello !

First of all, a big thank for your work and framework that is very useful for us!

I have recently tried to plug Load Time Weaving (LTW) in our application using Spring and AspectJ and I faced an issue: my aspect was not weaved.

It was due to the fact that the ClassFinder loads classes in base packages using the system class loader (see `org.jacpfx.rcp.util.ClassFinder.loadClass(String)`). Indeed, to be weaved, the class must be loaded thanks to the Spring `org.springframework.core.OverridingClassLoader` which does not always delegate to the parent class loader.

So, I think that
> return ClassLoader.getSystemClassLoader().loadClass(file);

should be replaced by

> return this.getClass().getClassLoader().loadClass(file);

Current workaround consists in locating the aspect outside of the JacpFX base packages.

Many thanks in advance,
Cheers,
Jean.

**Comment by amoAHCP** [comment]
Hi,
thank you...
i'll change it in the 2.1 branch and will test it. I can give you a hint when the snapshot is released, it would be nice when you can test it too.
THX
Andy

**Comment by jlepropre** [comment]
Hi,

Of course, I will test it!

Thanks,
Jean.

**Comment by amoAHCP** [comment]
Hi,
<dependency>
...
	<version>2.1-RC3</version>
</dependency>
 should be available on maven central.

Thanks,

Andy

**Comment by jlepropre** [comment]
Hi Andy,

Ok, thanks, I will test it asap.

Cheers,
Jean.

**Comment by jlepropre** [comment]
Hi Andy,

I have just tested it and it does not work unfortunately: it is my mistake in fact. The issue is not the reported one but it comes from the fact that packages scanning is done before initializing the Spring context. As it is done before, classes are loaded with a class loader which has not been yet instrumented.

So in `org.jacpfx.spring.launcher.AFXSpringXmlLauncher` and `org.jacpfx.spring.launcher.AFXSpringJavaConfigLauncher`, one should replace

>     @SuppressWarnings("unchecked")
    @Override
    public void start(Stage stage) throws Exception {
        initExceptionHandler();
        scanPackegesAndInitRegestry();
        final Launcher<ClassPathXmlApplicationContext> launcher = new SpringXmlConfigLauncher(getXmlConfig());
        final Class<? extends FXWorkbench> workbenchHandler = getWorkbenchClass();
        if (workbenchHandler == null) throw new ComponentNotFoundException("no FXWorkbench class defined");
        initWorkbench(stage, launcher, workbenchHandler);
    }

by

>     @SuppressWarnings("unchecked")
    @Override
    public void start(Stage stage) throws Exception {
        initExceptionHandler();
        final Launcher<ClassPathXmlApplicationContext> launcher = new SpringXmlConfigLauncher(getXmlConfig());
        scanPackegesAndInitRegestry();
        final Class<? extends FXWorkbench> workbenchHandler = getWorkbenchClass();
        if (workbenchHandler == null) throw new ComponentNotFoundException("no FXWorkbench class defined");
        initWorkbench(stage, launcher, workbenchHandler);
    }

and

>     @SuppressWarnings("unchecked")
    @Override
    public void start(Stage stage) throws Exception {
        initExceptionHandler();
        scanPackegesAndInitRegestry();
        final Launcher<AnnotationConfigApplicationContext> launcher = new SpringJavaConfigLauncher(getConfigClasses());
        final Class<? extends FXWorkbench> workbenchHandler = getWorkbenchClass();
        if (workbenchHandler == null) throw new ComponentNotFoundException("no FXWorkbench class defined");
        initWorkbench(stage, launcher, workbenchHandler);
    }

by

>     @SuppressWarnings("unchecked")
    @Override
    public void start(Stage stage) throws Exception {
        initExceptionHandler();
        final Launcher<AnnotationConfigApplicationContext> launcher = new SpringJavaConfigLauncher(getConfigClasses());
        scanPackegesAndInitRegestry();
        final Class<? extends FXWorkbench> workbenchHandler = getWorkbenchClass();
        if (workbenchHandler == null) throw new ComponentNotFoundException("no FXWorkbench class defined");
        initWorkbench(stage, launcher, workbenchHandler);
    }

I am really sorry for that mistake.

Cheers,
Jean.

**Comment by JacpFX** [comment]
Hi,
I’ll check it later today and give you a hint when I published a new version… from my side it should be ok to switch class loading and spring initialization.

Andy

**Comment by jlepropre** [comment]
Hi Andy,

Can I ask you if you got any chance to perform the change?

Thanks in advance for your answer!

Best regards,
Jean.

**Comment by amoAHCP** [comment]
Hi, sorry I am still at J1. I’ll try to make either today at the hackergarden or in the airplane tomorrow.

Andy

**Comment by amoAHCP** [comment]
Hi,
currently we have "return this.getClass().getClassLoader().loadClass(file);" .. in JacpFX3 it will change because I'll start to prepare it for Java9. Since a Java9 module has it's on classloader (perfect for me) this won't work. Be careful with this!

**Comment by jlepropre** [comment]
Fixed by 2.1-RC4.

Thank you very much!

Cheers,
Jean.
