### ISSUE TITLE
ClassFinder.extractClasses Expects "classes" as part of path.

### ISSUE THREAD

**Issue by smgonzales** [JacpFX/JacpFX#44]
Hi,

Nice work on the framework!

I've been exploring the framework in the Intellij IDE and found I was not able to run my project in the IDE with the default Intellij class output path.  

It appears the ClassFinder extractClasses method always expects a "classes" part of the file path, but that's the not the default that an Intellij IDE gives for a JavaFX project.  I'm able to change it in my project to make it work, but I thought I'd report what I found.

In particular the following lines from extractClasses will return an incorrect substring if classes is not found in the file path:

        String seperator = "classes".concat(File.separator);
        return (List)files.parallelStream().map((dir) -> {
            return dir.substring(dir.lastIndexOf(seperator) + 8, dir.length());
        }).filter((classDir) -> {
       ...
      
Thanks

Santiago

**Comment by amoAHCP** [comment]
Hi, JacpFX was written mostly using IntelliJ... are you using the archetype + maven or gradle? adopting JacpFX to a specific IDE has a low prio... with maven/gradle it is tested on IntelliJ, Netbeans, Eclipse on Linux, Mac and Windows.... so changing this will break a lot. You can provide a patch which should be tested on all those environments.

THX

Andy

**Comment by smgonzales** [comment]
Hi,

I was using the stable version 2.0.2, but I switched to 2.1 RC-3 today and you fixed the problem.  You changed how extract classes works so it no longer has problems when the classpath doesn't include the word "class".

Thanks again for providing this framework!  I'll continue to explore it and learn.

Santiago

**Comment by JacpFX** [comment]
Thank you

Andy
