### ISSUE TITLE
ResourceBundle injection in FXPerspective

### ISSUE THREAD

**Issue by jlepropre** [JacpFX/JacpFX#45]
Hi Andy,

It seems that resource bundle is never injected the first time a FXPerspective is accessed.

Indeed, in case of `FXPerspective`, resource bundle injection is done at line 253 of `org.jacpfx.rcp.handler.PerspectiveHandlerImpl.initComponent(Message<Event, Object>, Perspective<Node, EventHandler<Event>, Event, Object>)` (calling `org.jacpfx.rcp.util.FXUtil.performResourceInjection(Injectable, JacpContext<EventHandler<Event>, Object>)` which will use the resource bundle associated to the context) while the association of the resource bundle to the context will only be done at line 255 of `org.jacpfx.rcp.handler.PerspectiveHandlerImpl.initComponent(Message<Event, Object>, Perspective<Node, EventHandler<Event>, Event, Object>)` by the call to `org.jacpfx.rcp.handler.PerspectiveHandlerImpl.handlePerspectiveInitialization(Perspective<Node, EventHandler<Event>, Event, Object>)`.

Current workaround consists in getting the resource bundle from the context directly or in using the resource bundle provided as argument of the method annotated by @PostConstruct.

Note that everything works well for managed fragments.

Thanks in advance!

Cheers,
Jean.

**Comment by amoAHCP** [comment]
Hi.... can you provide the version of JacpFX (2.1-RC3 ?) 

Andy

**Comment by jlepropre** [comment]
Sorry. It is 2.1-RC3.

Jean.

**Comment by amoAHCP** [comment]
OK... so I pushed RC4 to maven central. I had very little time to test, hopefully nothing is broken... at least the UnitTests were fine ;-)
So let me know if both bugs are gone and thank you for your help.

Andy

**Comment by jlepropre** [comment]
Fixed by 2.1-RC4.

Thanks!

Jean.
