### ISSUE TITLE
ThrowableWrapper is not thread-safe

### ISSUE THREAD

**Issue by RAnders00** [JacpFX/JacpFX#48]
[`ThrowableWrapper`](https://github.com/JacpFX/JacpFX/blob/master/JACP.JavaFX/src/main/java/org/jacpfx/rcp/util/ThrowableWrapper.java) is not thread-safe, because it does not publish its invariants safely. You want to make its public field `final` or `volatile` (if writing is necessary)

Also, while you are at it, it might be a good idea to introduce a `equals`, `hashCode` and `toString` method as well.

**Comment by JacpFX** [comment]
OK, thanks for the hint... for some reason it was volatile before.

**Comment by amoAHCP** [comment]
Fix was already in JacpFX-3.0 branch, see org.jacpfx.concurrency.ThrowableWrapper.
