### ISSUE TITLE
some annotation conflict with java build-in package

### ISSUE THREAD

**Issue by gxz04220427** [JacpFX/JacpFX#50]
Hi,
I find some annotations used in jacpfx such as  @PostConstruct and @PreDestory is in the package `org.jacpfx.api.annotations`, but in the package ` javax.annotation` it also contain the @PostConstruct annotation. So I want to know what's the difference between these two annotations.
I want to integrate jacpfx into my springboot framework project. So I want to know how to operate these same name but in different package annotations.
In addition，I find a issue about springboot titled "[Spring Boot support](https://github.com/JacpFX/JacpFX/issues/12 )" , It's ok? 
Thank you!

**Comment by amoAHCP** [comment]
Hi, I had to introduce org.jacpfx.api.annotations since you can use JacpFX with many different DI containers and I wanted to avoid unwanted behavior. According to spring boot... I don't use it but there are many  people using it with JacpFX.

**Comment by gxz04220427** [comment]
Sorry,I can't find your introduce about org.jacpfx.api.annotations,could you give me a link? Thank you!!!

**Comment by amoAHCP** [comment]
Hi... I ment "I created org.jacpfx.api.annotations" to avoid conflicts with other DI containers. The reason is, that you can use JacpFX without Spring or with Guice,.... see documentation here: http://jacpfx.org/documentation_main.html#Annotations%20overview19

**Comment by gxz04220427** [comment]
....Oh,But,when I want to use jacpFx in my springboot project,I will face the problem that many same named annotations but different means.How could I solve this problem.Thank you!!!

**Comment by amoAHCP** [comment]
Hi, I'm not sure what you want to do... org.jacpfx.api.annotations.PostConstruct defines a Postconstruct for the JacpFX component (when it is ready to use)... If this JacpFX component is also a Spring bean (if you use it together with Spring) the javax.annotation.PostConstruct will be called when the Spring initialization is ready.... BUT you still have to wait until org.jacpfx.api.annotations.PostConstruct is called .... that are two different things. You are free to use both annotations in you component at the same time (@org.jacpfx.api.annotations.PostConstruct & @javax.annotation.PostConstruct), but they are triggered at different phases (first will be the Spring PostConstruct and than the JacpFX Postconstruct)... normally it would be enough to use the JacpFX PostConstruct...

**Comment by gxz04220427** [comment]
So,I think I get it,Thank you very much.I con't find any framework for javafx in china. Thank you!!!

**Comment by amoAHCP** [comment]
Have fune ;-)
