### ISSUE TITLE
Thread leaks and memory leaks when deactivating/activating components

### ISSUE THREAD

**Issue by mg-2014** [JacpFX/JacpFX#51]
When components are deactivated and activated again I can observe the "old" `EmbeddedFXComponentWorker` threads still active although they shouldn't be. The problem doesn't appear every time I debug the code. It seems to depend on where I put breakpoints and delay the execution. See thread "ControlView" in the attached "jvisualvm" screenshot:

![threads](https://cloud.githubusercontent.com/assets/9593044/18608990/66002716-7cf7-11e6-9d2d-ebafb092ecd4.png)

Since these threads reference `EmbeddedFXComponents` which in turn reference UI components there are memory leaks as well.

The problem seems to be that when `lock.unlock()` in `WorkerUtil:101` interrupts `getNextIncomingMessage()` in `EmbeddedFXComponentWorker:93` we immediately end up calling `handleComponentExecution()` again in line 82. (The line numbers correspond to the sources as they appear in version 2.1.)

There seems to be a `t.interrupt()` missing where the `InterruptedException` is caught (line 112):
```
        } catch (InterruptedException e) {
        	t.interrupt();
        } catch (Exception e) {
```

The same probably holds for `EmbeddedCallbackComponentWorker` (line 92). Maybe check other occurrences where `InterruptedException` is caught as well. I've found a couple of occurrences where `InterruptedException` is neither propagated nor the interrupted flag set.

The problems seems to exist in the current master version (`EmbeddedFXComponent:130`) as well. 

From what I gathered there is no `context.setActive()` to activate/deactive components anymore. Unfortunately I make heavy use of activating/deactivating components in my application.

**Comment by amoAHCP** [comment]
Hi Markus, 
thanks for your analysis... I'll take a look.


Andy

**Comment by amoAHCP** [comment]
Hi, i did some test and changed some lines... but in my case I cant't see the issue... the thread will be interrupted and no reference to EmbeddedFXComponent stays... anyway I created a JacpFX 2.1.1 branch. Maybe you can provide an example and test 2.1.1-SNAPSHOT on your own?

Thx

Andy

**Comment by mg-2014** [comment]
Hi Andy,
thanks. I will verify it at the weekend.

Concerning the use of `context.setActive()`... My use case is that I have menu items that open different views in the same target layout. Setting a single view to active state and all others to inactive state seemed to be the way to go. Thus I'm sending `activate` and `inactivate` messages and use `context.setActive()` in the handle() method.

**Comment by mg-2014** [comment]
With the current SNAPSHOT on {{JacpFX_2.1.1}} the issue seems to be fixed. I deactivated/activated the same component like 20 times and couldn't observe the issue anymore.
Thanks.
