### ISSUE TITLE
Problem with multiple active components in the same target layout when switching perspectives

### ISSUE THREAD

**Issue by mg-2014** [JacpFX/JacpFX#55]
The issue arises when there there are multiple components registered to the same target layout and you switch between perspectives. When switching to another perspective and then back, the components are added to the target layout in a different order or missing entirely.

In my example the target layout container is supposed to be a `StackPane`. Let's say you have 3 components A,B,C with C being displayed on top in the StackPane. When switching to another perspective and back you get C only. You do it again and you get A,B. And after a couple of times you get A,B,C again.

I came across the following code in `PerspectiveHandlerImpl`:
```
private static void bringRootToFront(final int index, final ObservableList<Node> children, final Node root) {
   if (index != 0) {
      children.remove(index);
      GridPane.setHgrow(root, Priority.ALWAYS);
      GridPane.setVgrow(root, Priority.ALWAYS);
      children.set(0, root);
   }
}
```

This looks as if the root node is actually not brought to the front but to the back and furthermore 
if the root node is found at index > 0 it is removed and overwrites the existing child node at index 0.

Shouldn't it rather be like this?
```
private static void bringRootToFront(final int index, final ObservableList<Node> children, final Node root) {
   if (index != children.size()-1) {
      children.remove(index);
      GridPane.setHgrow(root, Priority.ALWAYS);
      GridPane.setVgrow(root, Priority.ALWAYS);
      children.add(root);
   }
}
```

(Issue is related to version 2.1.)

**On a side node:**
Is there a way to switch between components registered to the same target layout in a way that only a single one is visible? What I do so far is activate the component I want to be visible and deactivate all others by `context.setActive()` (or more precisely: by sending "activate"/"deactivate" messages to the components which use `context.setActive()` in their `handle()` methods).
From what I gathered from the current master version `context.setActive()` isn't part of the regular `Context` interface anymore but instead there is an `updateActiveState() ` in the `InternalContext` which I'm probably not supposed to use as an application developer.

**Comment by amoAHCP** [comment]
Hi, it is not intended to put multiple components to one target layout. The idea is (in your case) to add containers to your StackPane and define them as target Layout (I know that you get one more container)... you could do:

StackPane main = ...
Group one =...
Group two = ...

main.getChildren().addAll(one,two);

perspectiveLayout.registerTargetLayoutComponent("one", one);
perspectiveLayout.registerTargetLayoutComponent("two", two);

**Comment by mg-2014** [comment]
Hi Andy,
OK. I'll try it the way you described and check if it works.
Thanks.

Concerning the `PerspectiveHandlerImpl`... Does that mean the code of `bringRootToFront()` is actually correct?

**Comment by tranquility79** [comment]
Can you please document this behaviour in http://jacpfx.org/documentation_main.html ? Today, I have spend a couple of hours for this issue.

**Comment by JacpFX** [comment]
OK

Andy
