### ISSUE TITLE
NPE if no workbench size is set.

### ISSUE THREAD

**Issue by tranquility79** [JacpFX/JacpFX#59]
@Workbench(id = "workbench", perspectives = { BaseConfiguration.PERSPECTIVE_MASTERDATA,
		BaseConfiguration.PERSPECTIVE_SEARCH})
public class MyWorkbench implements FXWorkbench {

	public void postHandle(FXComponentLayout layout) {
		System.out.println("postHandle");
	}

	public void handleInitialLayout(Message<Event, Object> action, WorkbenchLayout<Node> layout, Stage stage) {
		//layout.setWorkbenchXYSize(1024, 768);
	}
}

The error occurs because DefaultWorkspaceDecorator.defineScene assumes that the workbench size is set.

    private void defineScene() {
        final int x = getWorkbenchLayout().getWorkbenchSize().getX(); //error if no workbench size is set
        final int y = getWorkbenchLayout().getWorkbenchSize().getY();

        this.stage.setScene(new Scene(this.base, x, y));
        initCSS(this.stage.getScene());
    }

In the class AFXWorkbench the workbench layout is created via:

private final WorkbenchLayout<Node> workbenchLayout = new FXWorkbenchLayout();

Maybe you should set a default size? 

    private void initWorkbenchDecorator(Stage stage) {
        checkWorkbenchSize();
        workbenchDecorator.setWorkbenchLayout(getWorkbenchLayout());
        workbenchDecorator.initBasicLayout(stage);
        SceneUtil.setScene(stage.getScene());
    }

    private void checkWorkbenchSize() {
        Tupel<Integer, Integer> workBenchSize= getWorkbenchLayout().getWorkbenchSize();
        if(workBenchSize.getX()==null || workBenchSize.getY()==null) {
            //set a default size
            getWorkbenchLayout().setWorkbenchXYSize(DEFAULT_WORKBENCH_SIZE_X, DEFAULT_WORKBENCH_SIZE_Y);
        }
    }

Or initialize FXWorkbenchLayout with default values. :-)

**Comment by amoAHCP** [comment]
fixed in https://github.com/JacpFX/JacpFX/commit/e282829c4e18098e99bd59ed6ba5bf7010d924a8

**Comment by tranquility79** [comment]
Cool. Thx. 👍
