### ISSUE TITLE
Small issue in JavaDoc for SpringXmlConfigLauncher?

### ISSUE THREAD

**Issue by tranquility79** [JacpFX/JacpFX#60]
The JavaDoc says:

/**
- The SpringLaucher class resolves the **spring.xml** file and handles access to
- beans
  *
- @author Andy Moncsek
  *
  */

private final String BASIC_CONFIG_BEANS = "**basic.xml**";

**Comment by amoAHCP** [comment]
fixed in https://github.com/JacpFX/JacpFX/commit/0d5134842dbb430a89420e52b9510d917541e51a
