### ISSUE TITLE
Implementation multilingual using JacpFX?

### ISSUE THREAD

**Issue by anhnguyenbk** [JacpFX/JacpFX#61]
I have a perspective with two components.  When user switch to other languages, component will send a message to the perspective. In `handlePerspective` method, I call `Locate.setDefault()` to set corresponding locale and call `context.send(FXUtil.MessageUtil.INIT)` to init this perspective. But it not working at all.
I don't know how to implementation multilingual using JacpFX.  Anyone can help me? 
Thank you.

**Comment by trankimvu** [comment]
Why don't you share a few lines on what you did before you close the issue, Hoang Anh?

**Comment by anhnguyenbk** [comment]
Component render itself bring me to light :((
